version: "3.9"

services:
  app:
    build:
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./bungabucket_dev:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}